title = "Rottweiler vom Vaihinger Schloss"
baseURL = "https://grumpymikey.github.io/rottweilervomvaihingerschloss/"
#languageCode = "en-us"
languageCode = "de-de"
theme = "ananke"
copyright = "Rottweiler vom Vaihinger Schloss"


MetaDataFormat = "yaml"
#DefaultContentLanguage = "en"
DefaultContentLanguage = "de"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

# Github pages
publishDir = "docs"

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"


[params]
  favicon = ""
  description = ""
  # facebook = ""
  # twitter = ""
  # instagram = "https://www.instagram.com/rottweilervomvaihingerschloss/"
  # youtube = ""
  # github = ""
  # gitlab = ""
  # linkedin = ""
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-orange"
  # #EA5B0C
  # featured_image = "/background.jpg"
  recent_posts_number = 1
  # custom_css = ["css/puppeteer.css"]
  text_color = ""
  author = ""
  # Logo oben rechts
  site_logo = "images/RvVS_Logo_Kreis_weiss.png"
  [params.ananke_socials]
    #[params.ananke_socials.twitter]
    #  name = "twitter"
    #  url = "https://twitter.com/GoHugoIO"
    [params.ananke_socials.instagram]
      name = "instagram"
      url = "https://www.instagram.com/rottweilervomvaihingerschloss/"
  # [params.ananke_socials.adrk]
  #   name = "adrk-svg"
  #   # featured_image = "/images/winnie-castle.png"
  #   url = "https://adrk.de/index.php/de/"
  

[privacy]
  [privacy.disqus]
    disable = false
  [privacy.googleAnalytics]
    anonymizeIP = false
    disable = false
    respectDoNotTrack = false
    useSessionStorage = false
  [privacy.instagram]
    disable = false
    simple = false
  [privacy.twitter]
    disable = false
    enableDNT = false
    simple = false
  [privacy.vimeo]
    disable = false
    simple = false
  [privacy.youtube]
    disable = false
    privacyEnhanced = false


# TODO 
## Umbennen Posts in "News"
