title = "Rottweiler vom Vaihinger Schloss"
baseURL = "https://grumpymikey.github.io/rottweilervomvaihingerschloss/"
languageCode = "de-de"
theme = "ananke"
copyright = "Rottweiler vom Vaihinger Schloss"